name: Deploy Frontend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy Vue Frontend
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout source code
        uses: actions/checkout@v3

      - name: ğŸ”§ Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ— Build frontend
        run: npm run build

      - name: ğŸšš Upload dist to EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY_BASE64 }}
          source: "dist/*"
          target: "/home/ubuntu/frontend"

      - name: ğŸ” Fix permission & reload nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY_BASE64 }}
          script: |
            sudo chown -R www-data:www-data /home/ubuntu/frontend
            sudo chmod -R 755 /home/ubuntu/frontend
            sudo nginx -t && sudo systemctl reload nginx
